# Generated by Django 3.1.7 on 2021-03-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_html',
            field=models.CharField(default='000000', max_length=6, verbose_name='HEX code'),
        ),
    ]
