# Generated by Django 3.1.7 on 2021-03-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='download_link',
            field=models.CharField(max_length=500, null=True, verbose_name='Download link'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='brands/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=500, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
